services:
  mysql:
    image: mysql:8.0
    container_name: mysql_caprocam
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: caprocam
    ports:
      - "3307:3306"
    volumes:
      - mysql_caprocam_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_caprocam
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_caprocam_data:

  # <- Para arrancar se usa "docker compose up -d", y para acceder se usar "http://localhost:8080", el user y contraseña es "root"
  # Importante que la db usa el puerto 3307